### ISSUE TITLE
Normalize naming

### ISSUE THREAD

**Issue by miduga** [SUI-Components/SUIStudio#49]
So, project name is SUIStudio. Installable package is `@schibstedspain/sui-studio` and binary installed is `suistudio`. We should normalize naming because it's a mess.

**Comment by carlosvillu** [comment]
+1000

**Comment by naxhh** [comment]
Tell me about it...

```
history 1000 | grep "npm i -g"
 2776* npm i -g suistudio
 2777* npm i -g sui-studio
 2778* npm i -g @schibstedspain/sui-studio
```

**Comment by miduga** [comment]
xD

**Comment by davidbarna** [comment]
Solved in sui-studio@4
